#!/bin/sh

concurrently \
  --kill-others-on-fail \
  --names "Check Scripts,Check Styles,Check Types" \
  --prefix-colors "bgRed.bold,bgBlue.bold,bgCyan.bold" \
  "npm:lint:scripts --silent" \
  "npm:lint:styles --silent" \
  "npm:lint:ts --silent"
