#!/bin/sh

concurrently \
  --kill-others-on-fail \
  --names "Lint Staged,Build,Test" \
  --prefix-colors "yellow.bold,bgGreen.bold" \
  "npm:lint:staged --silent" \
  "npm:build --silent" \
  "npm:test --silent"
