#!/bin/sh

concurrently --names "Lints" --prefix-colors "yellow.bold" "npm:lint:fix --silent" &&
  echo &&
  concurrently --kill-others-on-fail --names "Build,Test" --prefix-colors "bgGreen.bold,bgMagenta.bold" "npm:build --silent" "npm:test --silent"
