#!/bin/sh

concurrently --names "Lints" --prefix-colors "yellow.bold" "npm:lint:fix --silent" &&
  echo &&
  concurrently --kill-others-on-fail --names "Build" --prefix-colors "bgGreen.bold" "npm:build --silent"
